version: "3.8"
services:
  api:
    platform: linux/amd64
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./tmp:/tmp
    command: java -Djava.security.egd=file:/dev/./urandom -jar /app.jar
    ports:
      - "8080:5050"
      - "35730:35729"
      - "5005:5005"